### ISSUE TITLE
Compare Testplugin to Watchdog   Folders and Files

### ISSUE THREAD

**Issue by rgleason** [rgleason/testplugin_pi#58]
@bdbcat 

Using Winmerge here are some screenshots, followed by some questions about what to do.

Should FindGTK3.cmake be copied into watchdog/cmake/libs?
Also this shows the other main TP folders which are all identical
```
circleci 
buildosx
ci
ci/extras
cmake
cmake/in-files
mingw
msvc

```
![Screenshot (1771)](https://github.com/rgleason/testplugin_pi/assets/2363959/b6ee0684-fee8-4c0f-9f59-f7a2856c3f89)

This screenshot shows the folders in libs that are the same.
It also show the folders that are missing from testplugin from watchdog. These folders are expanded.

Should these libs folders be copied from watchdog into testplugin?
Also the different nmea0183 folder is because watchdog has  *.bak files with small differences, otherwise the other files are the same.
```
curl
libtess2   <-- Would one of the other libtess in the glu folder suffice?
wxcurl
zlib-1.2.3

```

![Screenshot (1773)](https://github.com/rgleason/testplugin_pi/assets/2363959/e11e652c-d514-4c6d-ad0f-2c682c357725)

**Comment by bdbcat** [comment]
Leave watchdog alone now.  I am working this, and we will conflict.
Please leave wd, wr, wfax, and testplugin alone for a few days.  I am adapting them, in series, to submodule format.  Much easier if we don't conflict.
Choose another TP template plugin to work on, using streamline branch as before.
Remember that that "libs" from watchdog is the golden target.

**Comment by rgleason** [comment]
Comparing Testplugin with Weather_routing   there are no other folder or files for the libs directory, but FindGTK3.cmake should be copied to weather_routing_pi/libs ??

Comparing Testplugin with Weatherfax, I find that  FindPortaudio.cmake needs to be added to cmake.
Also weatherfax ha in buildwin/   portaudio_x86.dll, portaudio_x86.lib and PVW32Con.exe but those are unique to weatherfax.

When Testplugin is compared with Weatherfax the same Libs as Weather_routing appear to be needed in Testplugin.

**Comment by rgleason** [comment]
OK, I will get  Testplugin, Weather_routing and Weatherfax  LIBS to be the same as Watchdog and visa versa.
And any cmake file that is needed will also be copied to Watchdog.

**Comment by rgleason** [comment]
Oh, I see your comment above now. Wont touch now.
